[package]
name = "mod-downloader"
version = "0.1.0"
edition = "2024"

[dependencies]
libloading = "0.8.8"
log = "0.4.27"
log4rs = "1.3.0"
reqwest = "0.12.20"
serde = { version = "1.0.219", features = ["derive"] }
tokio = "1.45.1"
toml = "0.8.23"
