[package]
name = "starsector-neolauncher"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "crates/*"
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
game-launcher = { path = "crates/game-launcher" }
log = "0.4.27"
toml = "0.8.23"

[dependencies]
game-launcher = { path = "crates/game-launcher" }
log4rs = {version = "1.3.0", features = ["serde", "toml_format"]}
log = "0.4.27"
toml = "0.8.23"